FROM ruby:alpine

RUN apk add --update --no-cache \
      binutils-gold \
      build-base \
      curl \
      file \
      g++ \
      gcc \
      git \
      less \
      libstdc++ \
      libffi-dev \
      libc-dev \
      linux-headers \
      libxml2-dev \
      libxslt-dev \
      libgcrypt-dev \
      make \
      netcat-openbsd \
      nodejs \
      openssl \
      pkgconfig \
      postgresql-dev \
      python3 \
      tzdata \
      yarn \
      sqlite-dev

RUN gem install bundler

WORKDIR /app

COPY api42/Gemfile api42/Gemfile.lock ./

RUN bundle check || bundle install

COPY api42/package.json api42/yarn.lock ./

RUN yarn install --check-files

EXPOSE 3000

COPY api42/entrypoint.sh /usr/bin/

ENTRYPOINT ["entrypoint.sh"]